"""Make artist field optional for folk songs

Revision ID: 14637d76aaff
Revises: 4838d02f838b
Create Date: 2025-12-13 17:23:48.733838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14637d76aaff'
down_revision = '4838d02f838b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
