"""Add image_url column to songs

Revision ID: 4838d02f838b
Revises: 
Create Date: 2025-12-13 17:04:59.286402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4838d02f838b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'songs' not in tables:
        op.create_table(
            'songs',
            sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
            sa.Column('title', sa.String(length=100), nullable=False),
            sa.Column('artist', sa.String(length=100), nullable=True),
            sa.Column('song_key', sa.String(length=100), nullable=False),
            sa.Column('image_url', sa.String(length=512), nullable=True),
        )
    else:
        with op.batch_alter_table('songs', schema=None) as batch_op:
            cols = [c['name'] for c in inspector.get_columns('songs')]
            if 'image_url' not in cols:
                batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_song_key'), ['song_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_artist'), ['artist'], unique=False)
        batch_op.alter_column('song_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
