"""Add image_url column to songs

Revision ID: 4838d02f838b
Revises: 
Create Date: 2025-12-13 17:04:59.286402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4838d02f838b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('song_key',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_songs_artist'))
        batch_op.drop_index(batch_op.f('ix_songs_song_key'))
        batch_op.drop_index(batch_op.f('ix_songs_title'))
        batch_op.drop_column('data_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_song_key'), ['song_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_artist'), ['artist'], unique=False)
        batch_op.alter_column('song_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
